STATES = [
    "CREATED",
    "ENGINEERING_ANALYSIS",
    "RESOURCE_REQUESTED",
    "FINANCE_REVIEW",
    "FINANCE_REJECTED",
    "ENGINEERING_APPEAL",
    "FINANCE_REEVALUATION",
    "APPROVAL_REQUIRED",
    "WAITING_FOR_APPROVAL",
    "APPROVED",
    "REJECTED",
    "EXECUTING",
    "OPERATIONS_REVIEW",
    "COMPLETED",
    "FAILED",
    "PAUSED",
    "CANCELLED",
]

TRANSITIONS = {
    "CREATED": ["ENGINEERING_ANALYSIS", "PAUSED", "CANCELLED"],
    "ENGINEERING_ANALYSIS": ["RESOURCE_REQUESTED", "COMPLETED", "FAILED", "PAUSED", "CANCELLED"],
    "RESOURCE_REQUESTED": ["FINANCE_REVIEW", "FAILED", "PAUSED", "CANCELLED"],
    "FINANCE_REVIEW": ["FINANCE_REJECTED", "APPROVAL_REQUIRED", "APPROVED", "FAILED", "PAUSED", "CANCELLED"],
    "FINANCE_REJECTED": ["ENGINEERING_APPEAL", "REJECTED", "FAILED", "PAUSED", "CANCELLED"],
    "ENGINEERING_APPEAL": ["FINANCE_REEVALUATION", "FAILED", "PAUSED", "CANCELLED"],
    "FINANCE_REEVALUATION": ["APPROVAL_REQUIRED", "REJECTED", "FAILED", "PAUSED", "CANCELLED"],
    "APPROVAL_REQUIRED": ["WAITING_FOR_APPROVAL", "FAILED", "PAUSED", "CANCELLED"],
    "WAITING_FOR_APPROVAL": ["APPROVED", "REJECTED", "FAILED", "PAUSED", "CANCELLED"],
    "APPROVED": ["EXECUTING", "FAILED", "PAUSED", "CANCELLED"],
    "REJECTED": ["COMPLETED", "FAILED", "CANCELLED"],
    "EXECUTING": ["OPERATIONS_REVIEW", "FAILED", "PAUSED", "CANCELLED"],
    "OPERATIONS_REVIEW": ["COMPLETED", "FAILED", "PAUSED", "CANCELLED"],
    "COMPLETED": [],
    "FAILED": [],
    "PAUSED": ["ENGINEERING_ANALYSIS", "RESOURCE_REQUESTED", "FINANCE_REVIEW", "FINANCE_REJECTED",
                "ENGINEERING_APPEAL", "FINANCE_REEVALUATION", "APPROVAL_REQUIRED", "WAITING_FOR_APPROVAL",
                "APPROVED", "EXECUTING", "OPERATIONS_REVIEW", "COMPLETED", "CANCELLED"],
    "CANCELLED": [],
}


class InvalidTransitionError(Exception):
    def __init__(self, current: str, target: str):
        self.current = current
        self.target = target
        super().__init__(f"Invalid transition: {current} -> {target}")


def validate_transition(current: str, target: str) -> None:
    if current not in TRANSITIONS:
        raise InvalidTransitionError(current, target)
    allowed = TRANSITIONS[current]
    if target not in allowed:
        raise InvalidTransitionError(current, target)
